"""Слой `domain`: Pydantic-контракты между слоями и чистые правила.

Не импортирует ничего инфраструктурного и не делает I/O (ARCHITECTURE.md §3).
"""

from deckforge.domain.audit import (
    AuditReport,
    AuditSummary,
    CheckSpec,
    Finding,
    Scores,
)
from deckforge.domain.base import BBox, DomainModel
from deckforge.domain.content import (
    Asset,
    Brief,
    ContentPackage,
    Dataset,
    Fact,
    Number,
    Series,
)
from deckforge.domain.enums import (
    AutoFix,
    BlockType,
    CalloutTone,
    ChartType,
    ColorRef,
    Density,
    ExportFormat,
    FontRef,
    ImageFit,
    ImageSource,
    LayoutKind,
    Severity,
    SlideIntent,
    SmartArtPattern,
    TextRole,
)
from deckforge.domain.plan import DeckPlan, NarrativeCheck, SlidePlan
from deckforge.domain.slide import (
    Block,
    BulletItem,
    BulletsBlock,
    CalloutBlock,
    ChartBlock,
    DeckIR,
    FitResult,
    IconBlock,
    ImageBlock,
    KpiBlock,
    KpiItem,
    Provenance,
    QuoteBlock,
    SlideIR,
    SmartArtBlock,
    TableBlock,
    TextBlock,
)
from deckforge.domain.template import (
    ChartDefaults,
    Decor,
    DecorElement,
    Grid,
    LayoutCapacity,
    LayoutShape,
    LayoutSpec,
    Margins,
    PlaceholderSpec,
    ShapeKind,
    SlideSize,
    TemplateManifest,
    Theme,
    ThemeColors,
    ThemeFonts,
    TypographyStep,
)
from deckforge.domain.variants import VariantProfile

__all__ = [
    "Asset",
    "AuditReport",
    "AuditSummary",
    "AutoFix",
    "BBox",
    "Block",
    "BlockType",
    "Brief",
    "BulletItem",
    "BulletsBlock",
    "CalloutBlock",
    "CalloutTone",
    "ChartBlock",
    "ChartDefaults",
    "ChartType",
    "CheckSpec",
    "ColorRef",
    "ContentPackage",
    "Dataset",
    "DeckIR",
    "DeckPlan",
    "Decor",
    "DecorElement",
    "Density",
    "DomainModel",
    "ExportFormat",
    "Fact",
    "Finding",
    "FitResult",
    "FontRef",
    "Grid",
    "IconBlock",
    "ImageBlock",
    "ImageFit",
    "ImageSource",
    "KpiBlock",
    "KpiItem",
    "LayoutCapacity",
    "LayoutKind",
    "LayoutShape",
    "LayoutSpec",
    "Margins",
    "NarrativeCheck",
    "Number",
    "PlaceholderSpec",
    "Provenance",
    "QuoteBlock",
    "Scores",
    "Series",
    "Severity",
    "ShapeKind",
    "SlideIR",
    "SlideIntent",
    "SlidePlan",
    "SlideSize",
    "SmartArtBlock",
    "SmartArtPattern",
    "TableBlock",
    "TemplateManifest",
    "TextBlock",
    "TextRole",
    "Theme",
    "ThemeColors",
    "ThemeFonts",
    "TypographyStep",
    "VariantProfile",
]
